export default {
  colors: {
    foreground: '#111111',
    track: '#777777',
  },
  icons: {
    battery: '\udb84\udea3',
    brightness: '󰃟',
    cpu: '\udb83\udee0',
    dayProgress: '󱑸',
    disk: '\udb80\udeca',
    memory: '\udb80\udf5b',
    volume: '',
    wifi: '󰖩',
    weather: {
      clear: '',
      cloudy: '',
      rain: '',
      snow: '',
      thunder: '',
      fog: '',
      unknown: '',
    },
    players: {
      spotify: '',
      music: '',
      vlc: '󰕼',
      swinsian: '󰥛',
      vox: '',
    },
  },
  refresh: {
    clock: 1000,
    weather: 600000,
    nowPlaying: 5000,
    batteryLevel: 60000,
    brightnessLevel: 5000,
    cpuUsage: 5000,
    dayProgress: 60000,
    diskUsage: 120000,
    memoryUsage: 5000,
    volumeLevel: 5000,
    wifiSignal: 60000,
  },
  weather: {
    location: 'Saint_Petersburg,Russia',
  },
};
