export const config = {
  colors: {
    fg: '#111111',
    fgDark: '#BBD2E7',
    track: '#777777',
    trackDark: '#777777',
  },
  icons: {
    battery: '\uF240',
    brightness: '\uF042',
    cpu: '\uF2DB',
    dayProgress: '\uF017',
    disk: '\uF0A0',
    memory: '\uF1C0',
    volume: '\uF028',
    wifi: '\uF1EB',
    weather: {
      clear: '',
      cloudy: '',
      rain: '',
      snow: '',
      thunder: '',
      fog: '',
      unknown: '',
    },
    players: {
      spotify: '\uF1BC',
      music: '\uF001',
      vlc: '\uF008',
      swinsian: '\uF025',
      vox: '\uF025',
    },
  },
  refresh: {
    clock: 1000,
    weather: 600000,
    nowPlaying: 5000,
    batteryLevel: 60000,
    brightnessLevel: 5000,
    cpuUsage: 5000,
    dayProgress: 60000,
    diskUsage: 120000,
    theme: 10000,
    memoryUsage: 5000,
    volumeLevel: 5000,
    wifiSignal: 60000,
  },
  weather: {
    location: 'Saint_Petersburg,Russia',
  },
  positions: {
    disk: { top: '5rem', side: 'left' },
    volume: { top: '5rem', side: 'right' },
    memory: { top: '7.5rem', side: 'left' },
    brightness: { top: '7.5rem', side: 'right' },
    cpu: { top: '10rem', side: 'left' },
    wifi: { top: '10rem', side: 'right' },
    battery: { top: '12.5rem', side: 'left' },
    dayProgress: { top: '12.5rem', side: 'right' },
  },
  progressBar: {
    height: '2px',
  },
};
